version: '3.9'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpass
    networks:
      - carto_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: carto_si
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - carto_network

volumes:
  postgres_data:

networks:
  carto_network:
